name: 'Discord Release'
description:
  'Posts a message to a Discord webhook with links to GitHub, Curseforge and
  Modrinth projects'
author: 'Up'

branding:
  icon: 'message-square'
  color: 'blue'

inputs:
  modrinth-project-id:
    description: 'The project ID on Modrinth to link to'
    required: false
  curseforge-project-id:
    description: 'The project ID on CurseForge to link to'
  repository:
    description: 'The source repository to link to'
    required: false
    default: '${{ github.repository }}'
  project-name:
    description: 'The name of the project'
    required: false
  version:
    description: 'The display version'
    required: false
    default: '${{ github.ref_name }}'
  webhook-url:
    description: 'The webhook URL to send the message to'
    required: true
  thumbnail-url:
    description: 'The URL of the thumbnail to use'
    required: false
  ping-notification-role:
    description:
      'Whether to ping the notification role, by default will only ping if the
      version is not a pre-release'
    required: false
  notification-role-id:
    description: 'The role ID to ping'
    required: false

outputs:
  message:
    description: 'The message that was sent to the webhook'
  response_status:
    description: 'The status code received from the webhook'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/up-mods/action-discord-release:main'
  args:
    - "--modrinth-project-id=${{ inputs.modrinth-project-id }}"
    - "--curseforge-project-id=${{ inputs.modrinth-project-id }}"
    - "--project-name=${{ inputs.project-name }}"
    - "--project-version=${{ inputs.version }}"
    - "--project-repository=${{ inputs.repository }}"
    - "--discord-webhook-url=${{ inputs.webhook-url }}"
    - "--discord-thumbnail-url=${{ inputs.thumbnail-url }}"
    - "--discord-notification-role-id=${{ inputs.notification-role-id }}"
    - "--discord-ping-notification-role=${{ inputs.ping-notification-role }}"
