name: 'Discord Release'
description:
  'Posts a message to a Discord webhook with links to GitHub, Curseforge and
  Modrinth projects'
author: 'Up'

branding:
  icon: 'message-square'
  color: 'blue'

inputs:
  modrinth-project-id:
    description: 'The project ID on Modrinth to link to'
    required: false
  curseforge-project-id:
    description: 'The project ID on CurseForge to link to'
  repository:
    description: 'The source repository to link to'
    required: false
  project-name:
    description: 'The name of the project'
    required: false
  version:
    description: 'The display version'
    required: false
  webhook-url:
    description: 'The webhook URL to send the message to'
    required: true
  thumbnail-url:
    description: 'The URL of the thumbnail to use'
    required: false
  ping-notification-role:
    description: 'Whether to ping the notification role'
    required: false
    default: 'true'
  notification-role-id:
    description: 'The role ID to ping'
    required: false

outputs:
  message:
    description: 'The message that was sent to the webhook'

runs:
  using: node20
  main: dist/index.js
